common/models/Employee.php
<?php

namespace common\models;

use yii\db\ActiveQuery;

/**
 *Employee Model
 *
 * @property-read \yii\db\ActiveQuery $employeeBranches
 * @noinspection PropertiesInspection
 */
class Employee extends User
{
    public array $branches = [];

    public function rules()
    {
        return [
            [['first_name', 'last_name', 'father_name', 'username', 'phone', 'type', 'branches'], 'required'],
            [['first_name', 'last_name', 'father_name', 'phone'], 'string', 'max' => 255],
            [['type'], 'integer'],
            [['phone'], 'unique'],
            [['type'], 'in', 'range' => [self::TYPE_MANAGER, self::TYPE_ADMINSTRATOR]],
            [['branches'], 'each', 'rule' => ['exist', 'targetClass' => Branches::class, 'targetAttribute' => 'id']],
            ['username', 'trim'],
            ['username', 'unique']
        ];
    }

    public static function find()
    {
        return parent::find()
            ->andWhere([
                'in',
                'type',
                [
                    self::TYPE_MANAGER,
                    self::TYPE_ADMINSTRATOR,
                ],
            ]);
    }

    public function afterSave($insert, $changedAttributes)
    {
        EmployeeBranch::deleteAll(['user_id' => $this->id]);
        foreach ($this->branches as $branch) {
            $employeeBranch = new EmployeeBranch([
                'user_id' => $this->id,
                'branch_id' => $branch,
            ]);
            $employeeBranch->save();
        }
        parent::afterSave($insert, $changedAttributes);
    }

    public function afterFind()
    {
        $this->branches = EmployeeBranch::find()
            ->where(['user_id' => $this->id])
            ->select('branch_id')
            ->column();
        parent::afterFind();
    }

    public function getEmployeeBranches(): ActiveQuery
    {
        return $this->hasMany(EmployeeBranch::class, ['user_id' => 'id']);
    }
}

backend/controllers/EmployeeController.php
<?php

namespace backend\controllers;

use common\models\searchs\EmployeeSearch;
use common\models\Employee;
use yii\web\NotFoundHttpException;

/**
 * EmployeeController implements the CRUD actions for Employee model.
 */
class EmployeeController extends BaseController
{
    /**
     * Lists all Employee models.
     *
     * @return string
     */
    public function actionIndex()
    {
        $searchModel = new EmployeeSearch();
        $dataProvider = $searchModel->search($this->request->queryParams, Employee::find()->andWhere(['!=', 'user.status', Employee::STATUS_DELETED]));

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }


    public function actionArchive(): string
    {
        $searchModel = new EmployeeSearch();
        $dataProvider = $searchModel->search($this->request->queryParams, Employee::find()->andWhere(['=', 'user.status', Employee::STATUS_DELETED]));

        return $this->render('archive', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }


    public function actionChange($id)
    {
        $model = $this->findModel($id);
        $model->status = Employee::STATUS_ACTIVE;
        $model->save();
        return $this->redirect(\Yii::$app->request->referrer);
    }

    /**
     * Displays a single Employee model.
     * @param int $id ID
     * @return string
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Employee model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return string|\yii\web\Response
     * @throws \yii\base\Exception
     */
    public function actionCreate()
    {
        $model = new Employee();

        if ($this->request->isPost) {
            if ($model->load($this->request->post())) {
                $model->setPassword('12345678');
                $model->generateAuthKey();
                if ($model->save()) {
                    return $this->redirect(['view', 'id' => $model->id]);
                }

            }
        } else {
            $model->loadDefaultValues();
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Employee model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param int $id ID
     * @return string|\yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($this->request->isPost && $model->load($this->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Employee model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param int $id ID
     * @return \yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }


    public function actionForceDelete(int $id)
    {
        $this->findModel($id)->delete(true);

        return $this->redirect(['archive']);
    }


    /**
     * Finds the Employee model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param int $id ID
     * @return Employee the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Employee::findOne(['id' => $id])) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }

    public function actionActivate(int $id)
    {
        $employee = $this->findModel($id);
        $employee->status = Employee::STATUS_ACTIVE;
        $employee->save();

        return $this->redirect($this->request->referrer ?? ['index']);
    }
}

backend/views/employee/_form.php
<?php

use common\models\Employee;
use yii\bootstrap4\ActiveForm;
use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\Employee */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="card">
    <div class="card-body">

        <?php $form = ActiveForm::begin(); ?>

        <div class="row">
            <div class="col-md-4">
                <?= $form->field($model, 'first_name')->textInput(['maxlength' => true]) ?>
            </div>
            <div class="col-md-4">
                <?= $form->field($model, 'last_name')->textInput(['maxlength' => true]) ?>
            </div>
            <div class="col-md-4">
                <?= $form->field($model, 'father_name')->textInput(['maxlength' => true]) ?>
            </div>
        </div>

        <div class="row">
            <div class="col-md-4">
                <?= $form->field($model, 'username')->textInput(['maxlength' => true]) ?>
            </div>
            <div class="col-md-4">
                <?= $form->field($model, 'phone')->widget(\yii\widgets\MaskedInput::class, [
                    'mask' => '\+\9\9\8 99 999 99 99',
                    'options' => [
                        'minlength' => 17,
                    ]
                ]) ?>
            </div>
            <div class="col-md-4">
                <?= $form->field($model, 'type')->dropdownList([
                    Employee::TYPE_MANAGER => 'Boshqaruvchi',
                    Employee::TYPE_ADMINSTRATOR => 'Adminstrator',
                ]) ?>
            </div>
        </div>

        <?= $form->field($model, 'branches')->widget(\kartik\select2\Select2::class, [
            'data' => \common\models\Branches::getList(),
            'options' => [
                'placeholder' => 'Select a state ...',
                'multiple' => true,
                'id' => 'languages'
            ],
            'pluginOptions' => [
                'allowClear' => true
            ],
        ]) ?>

        <div class="row">
            <div class="col d-flex justify-content-end">
                <?= Html::submitButton('Saqlash', ['class' => 'btn btn-success']) ?>
            </div>
        </div>

        <?php ActiveForm::end(); ?>
    </div>
</div>

backend/views/employee/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model backend\models\searchs\EmployeeSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="employee-search">

    <?php $form = ActiveForm::begin([
    'action' => ['index'],
    'method' => 'get',
            'options' => [
        'data-pjax' => 1
        ],
        ]); ?>

        <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'username') ?>

    <?= $form->field($model, 'first_name') ?>

    <?= $form->field($model, 'last_name') ?>

    <?= $form->field($model, 'father_name') ?>

    <?php // echo $form->field($model, 'phone') ?>

    <?php // echo $form->field($model, 'auth_key') ?>

    <?php // echo $form->field($model, 'password_hash') ?>

    <?php // echo $form->field($model, 'password_reset_token') ?>

    <?php // echo $form->field($model, 'temp') ?>

    <?php // echo $form->field($model, 'photo') ?>

    <?php // echo $form->field($model, 'type') ?>

    <?php // echo $form->field($model, 'status') ?>

    <?php // echo $form->field($model, 'language') ?>

    <?php // echo $form->field($model, 'created_at') ?>

    <?php // echo $form->field($model, 'updated_at') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn
        btn-outline-secondary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/employee/archive.php
<?php

use yii\bootstrap4\Html;
use yii\grid\ActionColumn;
use yii\grid\GridView;
use yii\grid\SerialColumn;
use yii\widgets\Pjax;

/* @var $this yii\web\View */
/* @var $searchModel backend\models\searchs\NurseSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Filliallar (Arxiv)';
$this->params['breadcrumbs'][] = $this->title;
?>

<?php Pjax::begin(); ?>
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <div class="card-title">
                        Arxiv
                    </div>
                    <div class="card-tools">
                        <?= \yii\bootstrap4\Html::a('Faollar', ['employee/index'], [
                            'data-pjax' => 0
                        ]) ?>
                    </div>
                </div>
                <div class="card-body">

                    <?= GridView::widget([
                        'dataProvider' => $dataProvider,
//                        'filterModel' => $searchModel,
                        'columns' => [
                            ['class' => SerialColumn::class],

                            [
                                'attribute' => 'first_name',
                                'value' => static function (\common\models\Employee $employee) {
                                    return $employee->getFullName();
                                }
                            ],
                            [
                                'class' => \common\columns\StatusColumn::class
                            ],
                            [
                                'class' => ActionColumn::class,
                                'template' => '{view} {circle} {force-delete}',
                                'buttons' => [
                                    'circle' => static function ($url, $model, $key) {
                                        return Html::a('<i class="fa fa-recycle text-success"></i>', ['change', 'id' => $model->id], [
                                            'data' => [
                                                'pjax' => 0,
                                                'confirm' => "Siz rostdan ham ushbu elementni faollashtirmoqchimisiz?"
                                            ]
                                        ]);
                                    },
                                    'force-delete' => static function ($url, $model, $key) {
                                        return Html::a('<i class="fa fa-trash text-danger"></i>', $url, [
                                            'data' => [
                                                'pjax' => 0,
                                                'confirm' => "Siz rostdan ham to'liq ochirmoqchimisiz?"
                                            ]
                                        ]);
                                    },
                                ]
                            ],
                        ],
                    ]); ?>

                </div>
            </div>
        </div>
    </div>
<?php Pjax::end(); ?>

backend/views/employee/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\Employee */

$this->title = 'Ishchi Qo\'shish';
$this->params['breadcrumbs'][] = ['label' => 'Ishchilar', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;

echo $this->render('_form', [
'model' => $model,
]);

backend/views/employee/index.php
<?php

use common\models\Employee;
use yii\grid\ActionColumn;
use yii\grid\GridView;
use yii\helpers\Html;
use yii\widgets\Pjax;

/* @var $this yii\web\View */
/* @var $searchModel backend\models\searchs\EmployeeSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Ishchilar';
$this->params['breadcrumbs'][] = $this->title;
$this->params['create'] = Html::a('<i class="fa fa-plus"></i>', ['create'], ['class' => 'btn btn-success'])
?>

<?php Pjax::begin(); ?>
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <div class="card-title">
                        Faollar
                    </div>
                    <div class="card-tools">
                        <?= \yii\bootstrap4\Html::a('Arxiv', ['employee/archive'], [
                            'data-pjax' => 0
                        ]) ?>
                    </div>
                </div>
                <div class="card-body">
                    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

                    <?= GridView::widget([
                        'dataProvider' => $dataProvider,
                        'filterModel' => $searchModel,
                        'columns' => [
                            ['class' => 'yii\grid\SerialColumn'],
                            'first_name',
                            'last_name',
                            'phone',
                            [
                                'attribute' => 'type',
                                'value' => static function (Employee $employee) {
                                    return $employee->getTypeName();
                                },
                                'filter' => [
                                    Employee::TYPE_MANAGER => 'Boshqaruvchi',
                                    Employee::TYPE_ADMINSTRATOR => 'Adminstrator',
                                ],
                            ],
                            [
                                'class' => \common\columns\StatusColumn::class,
                                'filterList' => Employee::getStatusList(),
                            ],
                            [
                                'class' => ActionColumn::className(),
                            ],
                        ],
                    ]); ?>

                </div>
            </div>
        </div>
    </div>
<?php Pjax::end(); ?>

backend/views/employee/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\Employee */

$this->title = 'Ishchi ma\'lumotini tahrirlash: ' . $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Ishchilar', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Tahrirlash';

echo $this->render('_form', [
'model' => $model,
]);

backend/views/employee/view.php
<?php

use common\models\Employee;
use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model common\models\Employee */

$this->title = $model->getFullName();
$this->params['breadcrumbs'][] = ['label' => 'Ishchilar', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;

$this->params['update'] = Html::a('<i class="fa fa-pencil"></i>', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']);

$this->params['delete'] = $model->status === Employee::STATUS_ACTIVE ? Html::a('<i class="fa fa-trash"></i>', ['delete', 'id' => $model->id], [
    'class' => 'btn btn-warning',
    'data' => [
        'confirm' => 'Siz rostdan ham ushbu elementni o\'chirmoqchimisiz?',
        'method' => 'post',
    ],
]) : '';

$this->params['back'] = $model->status === Employee::STATUS_DELETED ? Html::a('<i class="fa fa-trash"></i>', ['force-delete', 'id' => $model->id], [
    'class' => 'btn btn-danger',
    'data' => [
        'confirm' => 'Siz rostdan ham ushbu elementni o\'chirmoqchimisiz?',
        'method' => 'post',
    ],
]) : '';
$this->params['other'] = !$model->isActive() ? Html::a('<i class="fa fa-recycle"></i>', ['activate', 'id' => $model->id], [
    'class' => 'btn btn-success',
    'data' => [
        'confirm' => 'Siz rostdan ham ushbu elementni faollashtirmoqchimisiz?',
        'method' => 'post',
    ],
]) : '';

?>

<div class="row">
    <div class="col-md-6">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">
                    Asosiy ma'lumotlar
                </h3>
            </div>
            <div class="card-body">
                <?= DetailView::widget([
                    'model' => $model,
                    'attributes' => [
                        'id',
                        'first_name',
                        'last_name',
                        'father_name',
                        'phone',
                        'username',
                        [
                            'attribute' => 'password',
                            'format' => 'raw',
                            'value' => static function (Employee $employee) {
                                return $employee->validatePassword('12345678') ? '<span class="text-success">' . 'Odatiy parol: 12345678' . '</span>' : '<span class="text-danger">' . 'Parol o\'zgartirilgan' . '</span>';
                            }
                        ],
                        [
                            'attribute' => 'type',
                            'value' => static function (Employee $nurseData) {
                                return $nurseData->getTypeName();
                            }
                        ],
                        [
                            'attribute' => 'branches',
                            'format' => 'raw',
                            'value' => static function (Employee $nurseData) {
                                $items = '';
                                foreach ($nurseData->employeeBranches as $branch) {
                                    $items .= "<li>{$branch->branch->name}</li>";
                                }
                                return "<ul>{$items}</ul>";
                            }
                        ],
                        [
                            'attribute' => 'status',
                            'value' => static function (Employee $nurse) {
                                return $nurse->getStatusName();
                            }
                        ],
                        'created_at:datetime',
                        'updated_at:datetime',
                    ],
                ]) ?>
            </div>
        </div>
    </div>
    <div class="col-md-6">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">
                    Rasmi
                </h3>
            </div>
            <div class="card-body">
                <?= Html::img($model->getPhotoUrl(), [
                    'class' => 'img-fluid img-circle',
                    'alt' => 'Nurse Data Photo',
                ]) ?>
            </div>
        </div>
    </div>
</div>