common/models/Speciality.php
<?php

namespace common\models;

use common\behaviors\DefaultMultilingualBehavior;
use common\models\defaults\DefaultActiveRecord;
use cranky4\changeLogBehavior\ChangeLogBehavior;
use yii\db\ActiveQueryInterface;

/**
 * This is the model class for table "speciality".
 *
 * @property int $id
 * @property string $name
 * @property int $status
 */
class Speciality extends DefaultActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'speciality';
    }


    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['name'], 'required'],
            [['status'], 'integer'],
            ['status', 'default', 'value' => self::STATUS_ACTIVE],
            [['name'], 'string', 'max' => 255],
        ];
    }

}

backend/controllers/SpecialityController.php
<?php

namespace backend\controllers;

use common\models\searchs\SpecialitySearch;
use common\models\Branches;
use common\models\Speciality;
use yii\web\NotFoundHttpException;

/**
 * SpecialityController implements the CRUD actions for Speciality model.
 */
class SpecialityController extends BaseController
{

    /**
     * Lists all Speciality models.
     *
     * @return string
     */
    public function actionIndex()
    {
        $searchModel = new SpecialitySearch();
        $dataProvider = $searchModel->search($this->request->queryParams, Speciality::find()->andWhere(['!=', 'status', Speciality::STATUS_DELETED]));

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }


    public function actionArchive(): string
    {
        $searchModel = new SpecialitySearch();
        $dataProvider = $searchModel->search($this->request->queryParams, Speciality::find()->andWhere(['=', 'status', Speciality::STATUS_DELETED]));

        return $this->render('archive', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionChange($id)
    {
        $model = $this->findModel($id);
        $model->status = Branches::STATUS_ACTIVE;
        $model->save();
        return $this->redirect(\Yii::$app->request->referrer);
    }

    /**
     * Displays a single Speciality model.
     * @param int $id ID
     * @return string
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Speciality model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return string|\yii\web\Response
     */
    public function actionCreate()
    {
        $model = new Speciality();

        if ($this->request->isPost) {
            if ($model->load($this->request->post()) && $model->save()) {
                return $this->redirect(['view', 'id' => $model->id]);
            }
        } else {
            $model->loadDefaultValues();
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Speciality model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param int $id ID
     * @return string|\yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($this->request->isPost && $model->load($this->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Speciality model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param int $id ID
     * @return \yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }


    public function actionForceDelete(int $id)
    {
        $this->findModel($id)->delete(true);

        return $this->redirect(['archive']);
    }

    /**
     * Finds the Speciality model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param int $id ID
     * @return Speciality the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Speciality::findOne(['id' => $id])) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

backend/views/speciality/_form.php
<?php

use yii\helpers\Html;
use yii\bootstrap4\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\Speciality */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="card">
    <div class="card-body">

        <?php $form = ActiveForm::begin(); ?>

            <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>



        <div class="row">
            <div class="col d-flex justify-content-end">
                <?= Html::submitButton('Saqlash', ['class' => 'btn
                btn-success']) ?>
            </div>
        </div>


        <?php ActiveForm::end(); ?>

    </div>
</div>

backend/views/speciality/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model backend\models\searchs\SpecialitySearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="speciality-search">

    <?php $form = ActiveForm::begin([
    'action' => ['index'],
    'method' => 'get',
            'options' => [
        'data-pjax' => 1
        ],
        ]); ?>

        <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'name') ?>

    <?= $form->field($model, 'status') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn
        btn-outline-secondary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/speciality/archive.php
<?php

use yii\bootstrap4\Html;
use yii\grid\ActionColumn;
use yii\grid\GridView;
use yii\grid\SerialColumn;
use yii\widgets\Pjax;

/* @var $this yii\web\View */
/* @var $searchModel backend\models\searchs\NurseSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Filliallar (Arxiv)';
$this->params['breadcrumbs'][] = $this->title;
?>

<?php Pjax::begin(); ?>
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <div class="card-title">
                        Arxiv
                    </div>
                    <div class="card-tools">
                        <?= \yii\bootstrap4\Html::a('Faollar', ['speciality/index'], [
                            'data-pjax' => 0
                        ]) ?>
                    </div>
                </div>
                <div class="card-body">

                    <?= GridView::widget([
                        'dataProvider' => $dataProvider,
//                        'filterModel' => $searchModel,
                        'columns' => [
                            ['class' => SerialColumn::class],

                            [
                                'attribute' => 'first_name',
                                'value' => static function (\common\models\Speciality $speciality) {
                                    return $speciality->name_uz;
                                }
                            ],
                            [
                                'class' => \common\columns\StatusColumn::class
                            ],
                            [
                                'class' => ActionColumn::class,
                                'template' => '{view} {circle} {force-delete}',
                                'buttons' => [
                                    'circle' => static function ($url, $model, $key) {
                                        return Html::a('<i class="fa fa-recycle text-success"></i>', ['change', 'id' => $model->id], [
                                            'data' => [
                                                'pjax' => 0,
                                                'confirm' => "Siz rostdan ham ushbu elementni faollashtirmoqchimisiz?"
                                            ]
                                        ]);
                                    },
                                    'force-delete' => static function ($url, $model, $key) {
                                        return Html::a('<i class="fa fa-trash text-danger"></i>', $url, [
                                            'data' => [
                                                'pjax' => 0,
                                                'confirm' => "Siz rostdan ham to'liq ochirmoqchimisiz?"
                                            ]
                                        ]);
                                    },
                                ]
                            ],
                        ],
                    ]); ?>

                </div>
            </div>
        </div>
    </div>
<?php Pjax::end(); ?>

backend/views/speciality/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\Speciality */

$this->title = 'Mutaxassislik Qo\'shish';
$this->params['breadcrumbs'][] = ['label' => 'Mutaxassislik', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;

echo $this->render('_form', [
'model' => $model,
]);

backend/views/speciality/index.php
<?php

use yii\grid\ActionColumn;
use yii\grid\GridView;
use yii\helpers\Html;
use yii\widgets\Pjax;

/* @var $this yii\web\View */
/* @var $searchModel backend\models\searchs\SpecialitySearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Mutaxassislik';
$this->params['breadcrumbs'][] = $this->title;
$this->params['create'] = Html::a('<i class="fa fa-plus"></i>', ['create'], ['class' => 'btn btn-success'])
?>
<?php Pjax::begin(); ?>
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <div class="card-title">
                        Faollar
                    </div>
                    <div class="card-tools">
                        <?= \yii\bootstrap4\Html::a('Arxiv', ['speciality/archive'], [
                            'data-pjax' => 0
                        ]) ?>
                    </div>
                </div>
                <div class="card-body">

                    <?php Pjax::begin(); ?>
                    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

                    <?= GridView::widget([
                        'dataProvider' => $dataProvider,
                        'filterModel' => $searchModel,
                        'columns' => [
                            ['class' => 'yii\grid\SerialColumn'],
                            'name',
                            [
                                'class' => \common\columns\StatusColumn::class,
                                'filterList' => \common\models\Speciality::getStatusList()
                            ],
                            [
                                'class' => ActionColumn::className(),
                            ],
                        ],
                    ]); ?>

                </div>
            </div>
        </div>
    </div>
<?php Pjax::end(); ?>

backend/views/speciality/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\Speciality */

$this->title = 'Mutaxassislikni tahrirlash: ' . $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Mutaxassislik', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->name, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Tahrirlash';

echo $this->render('_form', [
'model' => $model,
]);

backend/views/speciality/view.php
<?php

use common\models\Speciality;
use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model common\models\Speciality */

$this->title = $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Mutaxassislik', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;

$this->params['update'] = Html::a('<i class="fa fa-pencil"></i>', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']);
$this->params['delete'] = $model->status === Speciality::STATUS_ACTIVE ? Html::a('<i class="fa fa-trash"></i>', ['delete', 'id' => $model->id], [
    'class' => 'btn btn-warning',
    'data' => [
        'confirm' => 'Siz rostdan ham ushbu elementni o\'chirmoqchimisiz?',
        'method' => 'post',
    ],
]) : '';

$this->params['other'] = $model->status === Speciality::STATUS_DELETED ? Html::a('<i class="fa fa-trash"></i>', ['force-delete', 'id' => $model->id], [
    'class' => 'btn btn-danger',
    'data' => [
        'confirm' => 'Siz rostdan ham ushbu elementni o\'chirmoqchimisiz?',
        'method' => 'post',
    ],
]) : '';
?>

<div class="card">
    <div class="card-body">
        <?= DetailView::widget([
            'model' => $model,
            'attributes' => [
                'id',
                'name',
                [
                    'attribute' => 'status',
                    'value' => static function (\common\models\Speciality $speciality) {
                        return $speciality->getStatusName();
                    }
                ],
            ],
        ]) ?>
    </div>
</div>